# Five-cohort follow-up availability analysis; original data are read-only.
# Target for IPW: baseline complete-FI and common-score eligible participants whose follow-up status identifies them as alive (codes 1 or 4), within countries with at least one follow-up FI observation.
# Recorded deaths, unknown vital status and country-wave absence are tabulated separately.
options(stringsAsFactors=FALSE,warn=1)
try(Sys.setlocale('LC_ALL','Chinese (Simplified)_China.utf8'),silent=TRUE)
suppressPackageStartupMessages(library(haven))
script_file <- sub("^--file=", "", grep("^--file=", commandArgs(trailingOnly=FALSE), value=TRUE)[1])
package_dir <- Sys.getenv("MS5_PACKAGE_DIR", unset="")
if (!nzchar(package_dir)) package_dir <- dirname(dirname(normalizePath(script_file,winslash="/",mustWork=TRUE)))
source(file.path(package_dir,"code/00_config.R"),encoding="UTF-8")
out <- file.path(runtime_dir,"extensions/attrition");dir.create(out,recursive=TRUE,showWarnings=FALSE)
logfile<-file.path(out,'02_attrition_analysis.log');sink(logfile,split=TRUE);on.exit<-NULL
p<-readRDS(file.path(base,'prepared_data.rds'));folds<-readRDS(file.path(score_source,'FI_reduction_locked_scores.rds'));meta<-read.csv(file.path(package_dir,'mappings/baseline_variable_metadata.csv'),fileEncoding='UTF-8')
configs<-list(HRS=c(id='hhidpn',b='r14',f='r15'),ELSA=c(id='idauniq',b='r9',f='r10'),SHARE=c(id='mergeid',b='r2',f='r4'),CHARLS=c(id='ID',b='r3',f='r4'),MHAS=c(id='unhhidnp',b='r5',f='r6'))
cohs<-names(configs);allz<-list();statusmeta<-list();stage<-list();reason<-list();baselineaudit<-list();deadcheck<-list()
for(coh in cohs){
 f<-folds[[coh]];z<-p$main[match(f$uid,p$main$uid),];stopifnot(identical(z$uid,f$uid),isTRUE(all.equal(z$fi_complete,f$complete_FI)))
 if(coh=='SHARE'){srcountry<-readRDS(file.path(out,'SHARE_country_source.rds'));ci<-match(z$uid,srcountry$uid);stopifnot(all(!is.na(ci)));z$country<-srcountry$source_country_label[ci]};cf<-configs[[coh]];path<-source_file(unique(meta$source[meta$cohort==coh&meta$variable==paste0(cf['b'],'iwstat')])[1]);sv<-paste0(cf['f'],'iwstat');md<-read_dta(path,col_select=all_of(sv),n_max=0);labs<-attr(md[[sv]],'labels');numlabs<-labs[is.finite(labs)]
 for(j in seq_along(numlabs))statusmeta[[length(statusmeta)+1]]<-data.frame(cohort=coh,source=path,variable=sv,variable_label=attr(md[[sv]],'label'),code=as.numeric(numlabs[j]),value_label=names(numlabs)[j])
 z$common<-complete.cases(f$universal)&complete.cases(f$phenotype_score);z$retained<-z$common&is.finite(f$followup_FI);z$followup_FI<-f$followup_FI;z$FI6<-f$universal[,6];z$followup_frail<-f$followup_frail
 # Labels constitute the classification evidence; original numeric fu_dead is audited.
 deadcodes<-as.numeric(numlabs[grepl('died',names(numlabs),ignore.case=TRUE)&!grepl('dk|unknown',names(numlabs),ignore.case=TRUE)]);alivecodes<-as.numeric(numlabs[grepl('alive',names(numlabs),ignore.case=TRUE)&!grepl('dk|died',names(numlabs),ignore.case=TRUE)])
 z$status_group<-ifelse(is.na(z$fu_status),'Missing status',ifelse(z$fu_status %in% deadcodes,'Recorded death',ifelse(z$fu_status==1,'Respondent alive',ifelse(z$fu_status==4,'Nonrespondent alive',ifelse(z$fu_status==10,'Country absent from wave',ifelse(z$fu_status==9,'Unknown vital status','Other status'))))))
 z$known_alive<-z$fu_status %in% alivecodes;z$stage<-ifelse(!z$common,'Common-score requirement',ifelse(!is.finite(f$followup_FI),'Follow-up FI unavailable','Retained for follow-up FI'))
 z$female<-ifelse(is.na(z$gender),NA_real_,as.numeric(z$gender==2));dc<-c('hypertension','diabetes','heart_disease','cancer','stroke','arthritis','lung_disease');z$chronic_count<-rowSums(z[,dc],na.rm=FALSE);z$chronic_observed<-rowSums(!is.na(z[,dc]));z$adl_any<-ifelse(is.na(z$adl),NA_real_,as.numeric(z$adl>0));z$iadl_any<-ifelse(is.na(z$iadl),NA_real_,as.numeric(z$iadl>0));z$poor_srh<-ifelse(is.na(z$srh),NA_real_,as.numeric(z$srh>=4))
 baselineaudit[[coh]]<-data.frame(cohort=coh,n=nrow(z),age_min=min(z$age,na.rm=TRUE),age_max=max(z$age,na.rm=TRUE),age_lt65=sum(z$age<65,na.rm=TRUE),age_missing=sum(is.na(z$age)),baseline_complete_FI=sum(is.finite(z$fi_complete)),followup_status_missing=sum(is.na(z$fu_status)))
 deathactual<-z$fu_status %in% deadcodes;deadcheck[[coh]]<-data.frame(cohort=coh,labels_death_codes=paste(deadcodes,collapse=';'),labels_alive_codes=paste(alivecodes,collapse=';'),preprocessed_death_mismatch=sum(z$fu_dead!=deathactual,na.rm=TRUE))
 stage[[coh]]<-data.frame(cohort=coh,baseline_complete_FI_n=nrow(z),common_all_k_n=sum(z$common),common_score_excluded_n=sum(!z$common),followup_FI_unavailable_among_common_n=sum(z$common&!is.finite(z$followup_FI)),retained_n=sum(z$retained),retained_fraction=mean(z$retained))
 for(st in unique(z$stage))for(sg in unique(z$status_group)){ix<-z$stage==st&z$status_group==sg;reason[[length(reason)+1]]<-data.frame(cohort=coh,stage=st,status_group=sg,n=sum(ix))}
 allz[[coh]]<-z
}
write.csv(do.call(rbind,statusmeta),file.path(out,'followup_status_source_labels.csv'),row.names=FALSE,na='');write.csv(do.call(rbind,stage),file.path(out,'attrition_stage_counts.csv'),row.names=FALSE);write.csv(do.call(rbind,reason),file.path(out,'attrition_stage_by_status.csv'),row.names=FALSE);write.csv(do.call(rbind,baselineaudit),file.path(out,'baseline_age_status_audit.csv'),row.names=FALSE);write.csv(do.call(rbind,deadcheck),file.path(out,'preprocessed_death_classification_audit.csv'),row.names=FALSE)
# SMD = (retained mean - comparison mean) / pooled SD, evaluated in each variable's observed subset.
vars<-c(age='Age, years',female='Female',fi_complete='Baseline complete FI',chronic_count='Seven-condition burden',hypertension='Hypertension',diabetes='Diabetes',heart_disease='Heart disease',cancer='Cancer',stroke='Stroke',arthritis='Arthritis',lung_disease='Lung disease',married='Married or partnered',low_education='Low education',poor_srh='Fair or poor self-rated health',adl_any='Any baseline ADL limitation',iadl_any='Any baseline IADL limitation',walk_difficulty='Walking difficulty',fatigue='Fatigue',bmi_continuous='BMI',grip='Grip strength',fi_n_observed='Observed complete-FI items')
binary<-c('female','hypertension','diabetes','heart_disease','cancer','stroke','arthritis','lung_disease','married','low_education','poor_srh','adl_any','iadl_any','walk_difficulty','fatigue')
smd<-function(a,b){a<-a[is.finite(a)];b<-b[is.finite(b)];if(length(a)<2||length(b)<2)return(NA_real_);den<-sqrt((var(a)+var(b))/2);if(den==0)return(if(mean(a)==mean(b))0 else NA_real_);(mean(a)-mean(b))/den}
comparisons<-list();countryrows<-list()
for(coh in cohs){z<-allz[[coh]];comparegroups<-list(All_baseline=rep(TRUE,nrow(z)),Common_score_eligible=z$common,Known_alive_common=z$common&z$known_alive)
 for(cmp in names(comparegroups)){e<-comparegroups[[cmp]];a<-e&z$retained;b<-e&!z$retained
 for(v in names(vars)){x<-z[[v]];xa<-x[a];xb<-x[b];comparisons[[length(comparisons)+1]]<-data.frame(cohort=coh,comparison=cmp,variable=v,label=unname(vars[v]),type=if(v %in% binary)'binary' else 'continuous',retained_n=sum(a),comparison_n=sum(b),retained_observed_n=sum(is.finite(xa)),comparison_observed_n=sum(is.finite(xb)),retained_missing_n=sum(!is.finite(xa)),comparison_missing_n=sum(!is.finite(xb)),retained_mean=mean(xa,na.rm=TRUE),retained_sd=sd(xa,na.rm=TRUE),comparison_mean=mean(xb,na.rm=TRUE),comparison_sd=sd(xb,na.rm=TRUE),SMD=smd(xa,xb))}
 for(cc in unique(z$country)){xa<-as.numeric(z$country[a]==cc);xb<-as.numeric(z$country[b]==cc);countryrows[[length(countryrows)+1]]<-data.frame(cohort=coh,comparison=cmp,country=cc,retained_n=sum(a),comparison_n=sum(b),retained_count=sum(xa),comparison_count=sum(xb),retained_proportion=mean(xa),comparison_proportion=mean(xb),SMD=smd(xa,xb))}
 }
}
write.csv(do.call(rbind,comparisons),file.path(out,'baseline_retained_vs_unretained.csv'),row.names=FALSE,na='');write.csv(do.call(rbind,countryrows),file.path(out,'baseline_country_retention.csv'),row.names=FALSE,na='')
# Weighted pairwise AUC and weighted mid-distribution rank correlation; no outcome imputation.
w_auc<-function(y,s,w){ok<-is.finite(y)&is.finite(s)&is.finite(w)&w>0;y<-y[ok];s<-s[ok];w<-w[ok];if(length(unique(y))<2)return(NA_real_);o<-order(s);y<-y[o];s<-s[o];w<-w[o];g<-match(s,unique(s));pos<-rowsum(w*(y==1),g,reorder=FALSE)[,1];neg<-rowsum(w*(y==0),g,reorder=FALSE)[,1];sum(pos*(cumsum(neg)-neg/2))/(sum(pos)*sum(neg))}
w_midrank<-function(x,w){o<-order(x);g<-match(x[o],unique(x[o]));wg<-rowsum(w[o],g,reorder=FALSE)[,1];r<-(cumsum(wg)-wg/2)/sum(wg);ans<-numeric(length(x));ans[o]<-r[g];ans}
w_cor<-function(x,y,w){x<-w_midrank(x,w);y<-w_midrank(y,w);mx<-weighted.mean(x,w);my<-weighted.mean(y,w);sum(w*(x-mx)*(y-my))/sqrt(sum(w*(x-mx)^2)*sum(w*(y-my)^2))}
# Default sensitivity specification recorded before the model is run: median covariate imputation with missing indicators; age/FI splines; status-verified alive target; .05-.99 probability clip; 1st-99th percentile weight truncation.
modelvars<-c('age','female','fi_complete','chronic_count','married','low_education','adl_any','iadl_any','walk_difficulty','poor_srh')
ipwstats<-list();ipwdiag<-list();coefrows<-list();balance<-list();targetaudit<-list();B<-200L;set.seed(20261001)
fitweights<-function(q,returnfit=FALSE){r<-as.numeric(is.finite(q$followup_FI));nd<-q;pred<-character()
 for(v in modelvars){miss<-is.na(nd[[v]]);if(all(miss))next;nd[[v]][miss]<-median(nd[[v]],na.rm=TRUE);if(length(unique(nd[[v]]))<2)next;pred<-c(pred,if(v %in% c('age','fi_complete'))paste0('splines::ns(',v,', df=3)') else v);if(any(miss)&&any(!miss)){mn<-paste0(v,'_missing');nd[[mn]]<-as.numeric(miss);pred<-c(pred,mn)}}
 if(length(unique(nd$country))>1){nd$country<-factor(nd$country);pred<-c(pred,'country')};nd$observed<-r;fm<-reformulate(pred,response='observed');fit<-suppressWarnings(glm(fm,data=nd,family=binomial(),control=glm.control(maxit=100)));pr<-as.numeric(predict(fit,type='response'));pc<-pmin(pmax(pr,.05),.99);w0<-mean(r)/pc[r==1];caps<-quantile(w0,c(.01,.99),names=FALSE);wt<-pmin(pmax(w0,caps[1]),caps[2]);ix<-which(r==1);v<-c(FI6_AUROC=w_auc(q$followup_frail[ix],q$FI6[ix],wt),Full_FI_AUROC=w_auc(q$followup_frail[ix],q$fi_complete[ix],wt),FI6_rank_correlation=w_cor(q$FI6[ix],q$followup_FI[ix],wt),Full_FI_rank_correlation=w_cor(q$fi_complete[ix],q$followup_FI[ix],wt));if(returnfit)return(list(v=v,fit=fit,p=pr,clipped=pc,w_raw=w0,w=wt,ix=ix,caps=caps,formula=paste(deparse(fm),collapse=' ')));v}
for(coh in cohs){z<-allz[[coh]];q0<-z[z$common&z$known_alive,];supported_countries<-names(which(tapply(is.finite(q0$followup_FI),q0$country,sum)>0));country_supported<-q0$country %in% supported_countries;q<-q0[country_supported,];obs<-is.finite(q$followup_FI);targetaudit[[coh]]<-data.frame(cohort=coh,common_n=sum(z$common),known_alive_common_n=nrow(q0),country_zero_observation_excluded_n=sum(!country_supported),known_alive_target_n=nrow(q),observed_followup_FI_n=sum(obs),unobserved_followup_FI_n=sum(!obs),recorded_death_excluded_n=sum(z$common&z$status_group=='Recorded death'),unknown_status_excluded_n=sum(z$common&z$status_group %in% c('Unknown vital status','Missing status')),country_wave_absence_excluded_n=sum(z$common&z$status_group=='Country absent from wave'))
 if(sum(obs)<50||sum(!obs)<10){cat('IPW insufficient target',coh,'\n');next};ww<-fitweights(q,TRUE);u<-c(FI6_AUROC=w_auc(q$followup_frail[obs],q$FI6[obs],rep(1,sum(obs))),Full_FI_AUROC=w_auc(q$followup_frail[obs],q$fi_complete[obs],rep(1,sum(obs))),FI6_rank_correlation=cor(q$FI6[obs],q$followup_FI[obs],method='spearman'),Full_FI_rank_correlation=cor(q$fi_complete[obs],q$followup_FI[obs],method='spearman'))
 auditpath<-file.path(out,paste0('IPW_',coh,'_audit.rds'));cached<-if(file.exists(auditpath))readRDS(auditpath) else NULL;cohort_seed<-20261001L+match(coh,cohs);set.seed(cohort_seed);cache_ok<-!is.null(cached)&&!is.null(cached$bootstrap_seed)&&cached$bootstrap_seed==cohort_seed&&identical(q$uid,cached$target$uid)&&isTRUE(all.equal(coef(ww$fit),coef(cached$fit),tolerance=1e-12))&&nrow(cached$bootstrap)==B;boot<-if(cache_ok)cached$bootstrap else matrix(NA_real_,B,4,dimnames=list(NULL,names(u)));if(cache_ok)cat('Verified unchanged model: bootstrap reused',coh,'\n');for(bb in if(cache_ok)integer(0) else seq_len(B)){ix<-sample.int(nrow(q),nrow(q),replace=TRUE);boot[bb,]<-tryCatch(fitweights(q[ix,]),error=function(e)rep(NA_real_,4));if(bb %% 50==0){cat('Bootstrap',coh,bb,'of',B,'\n');flush.console()}}
 for(j in seq_along(u)){vv<-boot[,j];ci<-quantile(vv,c(.025,.975),na.rm=TRUE);ipwstats[[length(ipwstats)+1]]<-data.frame(cohort=coh,metric=names(u)[j],target='Known-alive common-score sample in countries with follow-up observations',target_n=nrow(q),observed_n=sum(obs),unweighted=u[j],IPW=ww$v[j],difference=ww$v[j]-u[j],IPW_CI_low=ci[1],IPW_CI_high=ci[2],bootstrap_success_n=sum(is.finite(vv)),bootstrap_B=B)}
 ipwdiag[[coh]]<-data.frame(cohort=coh,formula=ww$formula,converged=ww$fit$converged,target_n=nrow(q),observed_n=sum(obs),observability_fraction=mean(obs),fitted_probability_min=min(ww$p),fitted_probability_median=median(ww$p),fitted_probability_max=max(ww$p),probability_clip_low=.05,probability_clip_high=.99,clipped_low_n=sum(ww$p<.05),clipped_high_n=sum(ww$p>.99),raw_weight_min=min(ww$w_raw),raw_weight_max=max(ww$w_raw),truncation_low=ww$caps[1],truncation_high=ww$caps[2],truncated_low_n=sum(ww$w_raw<ww$caps[1]),truncated_high_n=sum(ww$w_raw>ww$caps[2]),final_weight_min=min(ww$w),final_weight_max=max(ww$w),effective_sample_size=sum(ww$w)^2/sum(ww$w^2))
 cf<-summary(ww$fit)$coefficients;coefrows[[coh]]<-data.frame(cohort=coh,term=rownames(cf),estimate=cf[,1],SE=cf[,2],z=cf[,3],p=cf[,4],row.names=NULL)
 for(v in modelvars){xx<-q[[v]];ok<-is.finite(xx);xo<-xx[obs];ok2<-is.finite(xo);wm<-weighted.mean(xo[ok2],ww$w[ok2]);mu<-mean(xx[ok]);den<-sd(xx[ok]);balance[[length(balance)+1]]<-data.frame(cohort=coh,variable=v,target_mean=mu,unweighted_observed_mean=mean(xo[ok2]),IPW_observed_mean=wm,target_SD=den,unweighted_standardized_difference=(mean(xo[ok2])-mu)/den,IPW_standardized_difference=(wm-mu)/den)}
 saveRDS(list(target=q[,c('uid','common','known_alive','followup_FI','followup_frail','FI6','fi_complete')],fit=ww$fit,probability=ww$p,retained_index=ww$ix,weight=ww$w,bootstrap=boot,bootstrap_seed=cohort_seed),file.path(out,paste0('IPW_',coh,'_audit.rds')))
 cat('IPW COMPLETE',coh,'\n');flush.console()
}
write.csv(do.call(rbind,targetaudit),file.path(out,'IPW_target_and_excluded_status_counts.csv'),row.names=FALSE);write.csv(do.call(rbind,ipwstats),file.path(out,'IPW_performance_sensitivity.csv'),row.names=FALSE);write.csv(do.call(rbind,ipwdiag),file.path(out,'IPW_weight_diagnostics.csv'),row.names=FALSE);write.csv(do.call(rbind,coefrows),file.path(out,'IPW_observability_model_coefficients.csv'),row.names=FALSE);write.csv(do.call(rbind,balance),file.path(out,'IPW_baseline_balance_diagnostics.csv'),row.names=FALSE,na='')
# Country/status summaries expose structural wave absence separately from individual loss.
s<-allz$SHARE;write.csv(as.data.frame(table(country=s$country,status=s$status_group,stage=s$stage)),file.path(out,'SHARE_country_status_stage.csv'),row.names=FALSE)
print(do.call(rbind,stage));print(do.call(rbind,ipwstats));cat('PASS: all aggregate counts, status labels, retained/unretained comparisons and survivor-conditional IPW outputs completed.\n');capture.output(sessionInfo(),file=file.path(out,'R_sessionInfo.txt'));sink()




