# Harmonized-task ADL endpoint sensitivity, with the locked item rankings and scores unchanged.
options(stringsAsFactors=FALSE,warn=1);try(Sys.setlocale('LC_ALL','Chinese (Simplified)_China.utf8'),silent=TRUE)
script_file <- sub("^--file=", "", grep("^--file=", commandArgs(trailingOnly=FALSE), value=TRUE)[1])
package_dir <- Sys.getenv("MS5_PACKAGE_DIR", unset="")
if (!nzchar(package_dir)) package_dir <- dirname(dirname(normalizePath(script_file,winslash="/",mustWork=TRUE)))
source(file.path(package_dir,"code/00_config.R"),encoding="UTF-8")
out<-file.path(runtime_dir,"extensions/attrition");dir.create(out,recursive=TRUE,showWarnings=FALSE);sink(file.path(out,"16_shared_five_ADL_sensitivity.log"),split=TRUE)
p<-readRDS(file.path(base,'prepared_data.rds'));f<-readRDS(file.path(score_source,'FI_reduction_locked_scores.rds'));tasks<-c('batha','dressa','eata','beda','toilta');labels<-c('Bathing','Dressing','Eating','Getting in or out of bed','Toileting');B<-200L;rows<-list();flows<-list();coding<-list();endpointQA<-list()
auc<-function(y,s){ok<-is.finite(y)&is.finite(s);y<-y[ok];s<-s[ok];np<-sum(y==1);nn<-sum(y==0);if(np==0||nn==0)return(NA_real_);(sum(rank(s,ties.method='average')[y==1])-np*(np+1)/2)/(np*nn)}
for(coh in names(f)){pl<-p$panels[[coh]];z<-f[[coh]];stopifnot(all(tasks %in% colnames(pl$deficits)),all(tasks %in% colnames(pl$followup_deficits)));uid<-pl$dates$uid;stopifnot(length(uid)==nrow(pl$deficits),!anyDuplicated(uid));ix<-match(z$uid,uid);stopifnot(all(!is.na(ix)));bb<-pl$deficits[ix,tasks,drop=FALSE];ff<-pl$followup_deficits[ix,tasks,drop=FALSE];stopifnot(all(bb %in% 0:1|is.na(bb)),all(ff %in% 0:1|is.na(ff)))
 bo<-rowSums(!is.na(bb));fo<-rowSums(!is.na(ff));bf<-bo==5&rowSums(bb,na.rm=TRUE)==0;fpositive<-rowSums(ff==1,na.rm=TRUE)>0;fy<-ifelse(fpositive,1,ifelse(fo==5,0,NA_real_));y<-ifelse(bf,fy,NA_real_);common<-complete.cases(z$universal)&complete.cases(z$phenotype_score);risk<-common&is.finite(y);primary<-common&is.finite(z$incident_adl)
 flows[[coh]]<-data.frame(cohort=coh,baseline_complete_FI_n=length(z$uid),common_score_n=sum(common),baseline_five_task_observed_n=sum(bo==5),baseline_five_task_free_n=sum(bf),baseline_free_common_score_n=sum(bf&common),followup_task_positive_n=sum(bf&common&fy==1,na.rm=TRUE),followup_all_five_negative_n=sum(bf&common&fy==0,na.rm=TRUE),followup_task_status_uncertain_n=sum(bf&common&is.na(fy)),analysis_n=sum(risk),events=sum(y[risk]),primary_cohort_specific_ADL_analysis_n=sum(primary),primary_ADL_events=sum(z$incident_adl[primary]))
 for(j in seq_along(tasks)){im<-pl$items[match(tasks[j],pl$items$item),];coding[[length(coding)+1]]<-data.frame(cohort=coh,task=tasks[j],task_label=labels[j],source=im$source,baseline_variable=im$baseline,followup_variable=im$followup,source_variable_label=im$label,coding=im$rule,baseline_observed_n=sum(!is.na(bb[,j])),followup_observed_n=sum(!is.na(ff[,j])),baseline_task_positive_n=sum(bb[,j]==1,na.rm=TRUE),followup_task_positive_n=sum(ff[,j]==1,na.rm=TRUE))}
 yy<-y[risk];ss<-z$universal[risk,6];full<-z$complete_FI[risk];est<-c(FI6_AUROC=auc(yy,ss),Full_FI_AUROC=auc(yy,full));est<-c(est,AUROC_difference=est[1]-est[2],Above_chance_AUROC_retention=(est[1]-.5)/(est[2]-.5));names(est)<-c('FI6_AUROC','Full_FI_AUROC','AUROC_difference','Above_chance_AUROC_retention');boot<-matrix(NA_real_,B,4,dimnames=list(NULL,names(est)));set.seed(20261020+match(coh,names(f)));for(b in seq_len(B)){i<-sample.int(length(yy),length(yy),replace=TRUE);a<-auc(yy[i],ss[i]);af<-auc(yy[i],full[i]);boot[b,]<-c(a,af,a-af,if(af>.5)(a-.5)/(af-.5) else NA_real_)}
 for(j in seq_along(est)){ci<-quantile(boot[,j],c(.025,.975),na.rm=TRUE);rows[[length(rows)+1]]<-data.frame(cohort=coh,endpoint='Incident limitation in shared five ADL tasks',metric=names(est)[j],n=length(yy),events=sum(yy),estimate=unname(est[j]),CI_low=ci[1],CI_high=ci[2],bootstrap_B=B,bootstrap_success_n=sum(is.finite(boot[,j])))}
 endpointQA[[coh]]<-data.frame(cohort=coh,primary_and_shared_overlap_n=sum(primary&risk),primary_and_shared_both_observed_discordant_n=sum(z$incident_adl[primary&risk]!=y[primary&risk]),shared_endpoint_only_n=sum(risk&!primary),primary_endpoint_only_n=sum(primary&!risk))
 # Store the audit within the private analysis folder; public release uses aggregate results.
 saveRDS(list(uid=z$uid,baseline_task_observed=bo,baseline_task_free=bf,followup_task_observed=fo,followup_endpoint=fy,incident_ADL=y,common=common,risk=risk,bootstrap=boot),file.path(out,paste0('Shared_five_ADL_',coh,'_audit.rds')));cat('Shared-five ADL',coh,'n',sum(risk),'events',sum(yy),'FI6 AUC',est[1],'full AUC',est[2],'retention',est[4],'\n')
}
write.csv(do.call(rbind,rows),file.path(out,'shared_five_ADL_performance_sensitivity.csv'),row.names=FALSE,na='');write.csv(do.call(rbind,flows),file.path(out,'shared_five_ADL_sample_flow.csv'),row.names=FALSE);write.csv(do.call(rbind,coding),file.path(out,'shared_five_ADL_task_source_coding.csv'),row.names=FALSE);write.csv(do.call(rbind,endpointQA),file.path(out,'shared_five_ADL_endpoint_comparison.csv'),row.names=FALSE);cat('PASS: all five tasks observed in baseline and follow-up panels for all five cohorts; paired-bootstrap AUROC/retention sensitivity completed.\n');sink()

